server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${DB_DOMAIN}:${DB_PORT}/candy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
    url: ENC(I3WC6f7XbissxnqTpHqW/U84u9kB/8Gofpedx34pZhbYUegQSUhzFwVfV3UvtFntZ+5tcWBhzQGfR/iTAb9Trg+OqunykgGyFZtAmlpVQ915PtK8RznH56xyhdKInCj5zpotQiYOzkA=)
    username: ENC(I8pMeRhANPbTigt8FCD40g==)
    password: ENC(6q5oI1uTTpEEl/8Xx7O6rOyHX1sZmp77)